- README.md
npm install step is missing in README.md
> npm install step

- src/components/stepOne.js
> Fix bug in loading step one

- package.json
- src/components/stepFour.js
- src/utils/constants.js
- src/utils/utils.js
-implement pdf functionality download from step4
> (feature) implement pdf with data from step 4

- package.json
- src/components/Footer/index.js
- src/components/Header/index.js
- src/components/Home/index.js
- src/components/invest/index.js
- src/stores/Contracts.js
- src/stores/PricingStrategies.js
- src/stores/ReservedTokens.js
- src/stores/ReservedTokensInput.js
- src/stores/ReserveredTokensElements.js
- src/stores/StepThreeValidations.js
- src/stores/StepTwoValidations.js
- src/stores/Tiers.js
- src/stores/Token.js
It looks like the formatting of indentation is not correct as shown.  However the indentation is correct on my IDE with a tabsize of 2 spaces.
> (refactor) add mobx state stores

- package.json
- src/components/crowdsale/index.js
- src/components/crowdsale/utils.js
- src/components/invest/index.js
- src/components/stepFour/index.js
- src/components/stepFour/utils.js
- src/components/stepThree/index.js
- src/utils/blockchainHelpers.js
- src/utils/microservices.js
- src/utils/utils.js
web3 0.19 -> web3 1.0; 
twice callback from contract deployment fix; 
multiple transactions for crowdsale with reserved tokens fix
> Users` bugs feedback

- src/components/stepFour/index.js
- src/utils/utils.js
Related to https://github.com/oraclesorg/ico-wizard/issues/274
> (Fix) roundToDecimals function updating to cover all use case

- .gitmodules
- src/components/stepFour/utils.js
> Allow decimals for reserved tokens in percents

- README.md
- src/components/invest/index.js
- src/components/stepFour/index.js
- src/components/stepFour/utils.js
- src/utils/blockchainHelpers.js
- src/utils/constants.js
- src/utils/utils.js
+ upstream from Stage to Bridge at ICO Wizard side
+ Deposit event for reserved tokens distribution
> (Bridge): Important update to Bridge + ICO Wizard instruction to make it works

- src/utils/utils.js
I was testing the wizard against the testrpc and ran into an issue that, I think, is caused by this.
> Fix contract name

- src/utils/utils.js
> (Stage) Fix for #313

- src/components/stepFour/index.js
> Tokens should be immovable after finalizing at the left side of the bridge

- package.json
- src/components/invest/constants.js
- src/components/invest/index.js
- src/components/stepFour/index.js
Closes #320.
- Added react-alert (https://github.com/schiehll/react-alert) to display simple messages to the user.
- Informs the user that the invest transaction was rejected.
> (Fix) Investment Transaction rejection

- src/components/stepFour/index.js
> (Emergency) Increase gasLimit for updateJoinedCrowdsalesRecursive

- src/components/invest/index.js
> (Fix) Invest now to Contribute now

- src/components/stepFour/index.js
- src/components/stepFour/utils.js
- src/utils/blockchainHelpers.js
- src/utils/constants.js
This solves the first part of #269. The name of the downloaded file is generated using the current network and the address of the token.
> (Feature) Generate downloaded file name dynamically

- src/components/Common/CrowdsaleBlock.js
- src/components/Common/RadioInputField.js
- src/components/Common/ReservedTokensInputBlock.js
- src/components/Common/config.js
- src/components/Footer/index.js
- src/components/Home/index.js
- src/components/crowdsale/index.js
- src/components/crowdsale/utils.js
- src/components/invest/index.js
- src/components/stepFour/index.js
- src/components/stepFour/utils.js
- src/components/stepOne/index.js
- src/components/stepThree/index.js
- src/components/stepThree/utils.js
- src/components/stepTwo/index.js
- src/utils/blockchainHelpers.js
- src/utils/microservices.js
- src/utils/utils.js
> (Refactor) Remove all commented code

- package.json
- src/components/Common/CrowdsaleBlock.js
- src/components/Common/InputField.js
- src/components/Common/InputField.spec.js
- src/components/Common/ReservedTokensInputBlock.js
- src/components/Common/ReservedTokensItem.js
- src/components/Common/WhitelistInputBlock.js
- src/components/stepOne/index.js
- src/components/stepThree/index.js
- src/components/stepTwo/index.js
- src/utils/constants.js
This feature is simple, but I had to do some serious refactor around some components. I'll describe here what I had to do and some anti-patterns that I think we should avoid.
1. Avoid mutating React state. Things like:
```js
const state = this.state
state.some.deep.object.var = 'foo'
this.setState(state)
```
should be avoided. Sadly, there is no easy alternative that I'm aware of. The underlying problem is that React components should not have state with deep objects, but that's harder to fix. The best thing I found was [immutability-helper](https://github.com/kolodny/immutability-helper). Using that, the previous example becomes:
```js
const newState = update(this.state, {
some: {
deep: {
object: {
var: { $set: 'foo' }
}
}
}
})
```
It has some issues IMO, but it works and it's …
> (Feature) Validate addresses used in reserved tokens

- package.json
- src/components/Common/CrowdsaleBlock.js
- src/components/Common/InputField.js
- src/components/Common/ReservedTokensInputBlock.js
- src/components/Common/ReservedTokensItem.js
- src/components/Common/WhitelistInputBlock.js
- src/components/stepOne/index.js
- src/components/stepThree/index.js
- src/components/stepTwo/index.js
- src/utils/constants.js
Bugs with multiple tiers.
Reverting of this PR https://github.com/oraclesorg/ico-wizard/pull/358
Issue: https://github.com/oraclesorg/ico-wizard/issues/285
> (Emergency) Revert 358 validate addresses

- src/stores/Web3Store.js
> (Fix) Blank screen when MetaMask is not installed

- src/components/crowdsale/index.js
- src/components/crowdsale/utils.js
- src/components/invest/index.js
- src/components/stepFour/index.js
- src/components/stepFour/utils.js
- src/components/stepOne/index.js
- src/utils/blockchainHelpers.js
- src/utils/microservices.js
- src/utils/utils.js
Closes #318 
Mostly of the code was replaced with promises. There are still parts in the utility files that keeps using callbacks.
Tested with **testrpc**, with and without `--blocktime` flag, and in **rinkeby** test net.
> (Feature) Callbacks to promises

- src/components/stepFour/index.js
- src/stores/TierStore.js
> (Fix) Global min cap

- README.md
The README has a merge conflict committed.
> (Fix) Fix README.md

- .travis.yml
added integration with security testing tool CoPilot by BlackDuck
> (Fix) Integration with automation security testing tool 

- src/components/stepFour/index.js
- src/utils/blockchainHelpers.js
Closes #420 
- Added tier name parameter
- Due to the new parameter, contract deploy requires a bit more of gas, so the estimatedGasMax was increased.
- Updated `oracles-token-market-net-ico` submodule, to point to https://github.com/poanetwork/ico/commit/1ee74d3181ceb2bac3b606d4d279b452c4a87d5c
> (Fix) Include tier name

- src/components/manage/utils.js
This PR is the fifth step towards the completion of #323
- Retrieves tier's name from contract
> (Fix) Added Tier name support

- src/components/stepFour/utils.js
Closes #424 
- Changed method name
- Updated submodule
> (Fix) Change method name for whitelist

- src/components/invest/index.js
> (Fix) Duplicated Total Supply

- src/utils/constants.js
- src/utils/utils.js
> (Fix) Decimals validation

- src/components/invest/index.js
> (Fix) balance always zero

- src/components/stepThree/index.js
- src/utils/alerts.js
Relates to https://github.com/poanetwork/ico-wizard/issues/472
> (Emergency) Mainnet is down for maintenance alert

- src/components/Common/config.js
Closes #478 
**Problem**: ICO config example is not valid due to ESLint validation.
**Solution**: Update ICO config demo with valid example
> (Fix) Valid ICO config example

- package-lock.json
- package.json
- src/components/stepThree/utils.js
Closes #493 
Closes #494
**Problem**: Wrong format `YYYY-DD-MMTHH:mm`
**Solution**: Change format to `YYYY-MM-DDTHH:mm`
> (Emergency) Wrong default start time value format

- .github/ISSUE_TEMPLATE.md
Add information how to save log
> (Fix) Update ISSUE_TEMPLATE.md

- src/components/stepThree/utils.js
Relates to https://github.com/poanetwork/ico/pull/12, https://github.com/poanetwork/ico/pull/13
**Problems**: 
- Updating of existing reserved tokens object causes increasing of reserved tokens array
- We don't check if address is empty in `setReservedTokensListMultiple` method
**Solutions**: 
- Check if address in `setReservedTokensListMultiple` method is not empty
- Check, if address is already added to reserved tokens before
> (Fix) Reserved tokens minor update

- src/components/Footer/index.js
**Problem**: Footer year is outdated
**Solution**: Change to dynamic definition
> (Fix) Dynamic year in footer

- src/components/stepFour/index.js
- src/components/stepTwo/index.js
- src/utils/constants.js
- src/utils/utils.js
Closes #501 
**Problem**: Current max length of the token ticker is three.
**Solution**: Increase it to five.
> (Feature) five token ticker support

- src/components/invest/index.js
**Problem**: There is no info, from where sample invest transaction is. The users are confused.
**Solution**: Clarify, that sample transaction is from Kovan network
> (Fix) Sample invest tx text fix

- src/components/stepFour/index.js
- src/components/stepFour/utils.js
- src/utils/blockchainHelpers.js
- src/utils/constants.js
Closes #460 
Calculates gas and sets a default maximum gasLimit for all the tx in the deployment process.
> (Fix) Calculate gas for tx

- package-lock.json
- package.json
- src/components/crowdsale/index.js
- src/components/crowdsale/utils.js
- src/components/invest/index.js
- src/utils/utils.js
Fixes #528.
The same bug was happening with the number of tokens bought.
The fix is in the last commit, the other commits are refactors that I needed to do to make the code easier to understand. I recommend reviewing this PR commit by commit, it will probably be much easier.
> (Fix) UI bug when going from crowdsale to invest and back again

- src/components/stepFour/index.js
- src/components/stepFour/utils.js
- src/utils/blockchainHelpers.js
Closes https://github.com/poanetwork/ico-wizard/issues/544
Gas price for `add` method of `Registry` contract is from API (as we do for all other methods).
> (Fix) Add to registry fix

- src/components/stepThree/index.js
Reverts poanetwork/token-wizard#488
> Revert "(Emergency) Mainnet is down for maintenance warning due to audit"

- README.md
> (Fix) Travis badge update

- src/components/manage/index.js
Reverts poanetwork/token-wizard#556
due to https://github.com/poanetwork/token-wizard/pull/556#issuecomment-363105877
> Revert "(Fix) Allow finalize after distribute tokens"

- src/components/Common/PreventRefresh.js
- src/components/stepFour/index.js
This is an intermediate solution before #529.
Alerts the user if he/she is about to leave or refresh the current page (this is active in step four only)
> (Feature) Create component to prevent page refresh

- src/components/manage/index.js
Closes #541 
With fixes pointed in: https://github.com/poanetwork/token-wizard/pull/556#issuecomment-363105877
> 1. isMinimumGoalReached every time is true because the token wizard doesn't use soft cap. It is always zero. isCrowdsaleFull property instead checks that crowdsale is reached hard cap.
> 2. When we get properties like finalized, areReservedTokensDistributed we should call them from the last tier. So we need to call getLastTier in the current contract and then call all these properties from the last tier contract.
> (Fix) method to verify if crowdsale can be finalized

- src/components/manage/index.js
- src/utils/alerts.js
> (Feature) Alert if not the owner and prevent editing

- src/components/invest/index.js
- src/components/manage/index.js
- src/components/stepFour/index.js
- src/components/stepThree/CrowdsaleBlock.js
- src/components/stepThree/index.js
- src/utils/constants.js
Change `ICO` naming to `Crowdsale` in description of Invest and step 3 pages
> (Fix) ICO -> Crowdsale

- .eslintrc
- .travis.yml
- package-lock.json
- package.json
- src/components/Common/NumericInput.spec.js
- src/components/Common/ReservedTokensInputBlock.spec.js
- src/components/crowdsale/index.js
- src/components/invest/index.js
- src/components/manage/index.js
- src/modules.js
- src/stores/GasPriceStore.spec.js
- src/stores/autosave.js
- src/stores/utils.js
- src/utils/microservices.js
- src/utils/utils.js
Closes #609.
The tests were failing because of a cyclic dependency. This is not the first time that we have a problem caused by that, so I added an eslint plugin to check that there are no cyclic dependencies.
This was happening because `utils/utils.js` was using the stores, and some stores were using `utils/utils.js`. So I moved the util methods that depended on the stores to a new module `stores/utils.js`.
Besides that, this PR:
- Adds another rule from that plugin, `no-unresolved`, to get an error if an imported module does not exist (web3 is ignored because of the way we install it).
- Adds a step to the CI for running the linter
- Fixes an annoying warning with mobx.
> (Fix) Fix travis build

- src/components/Common/NumericInput.spec.js
- src/components/stepThree/index.js
- src/stores/TierStore.js
- src/utils/constants.js
- src/utils/utils.js
- src/utils/utils.spec.js
Closes #571 
Implements NumericInput component with integers equal or greater than 0.
> (Fix) Letter e in decimals and mincap

- src/utils/utils.js
- src/utils/utils.spec.js
> (Fix) Prevent special symbols for ticker

- src/components/Common/InputField.js
- src/components/Common/NumericInput.js
- src/components/Common/__snapshots__/NumericInput.spec.js.snap
- src/components/Common/__snapshots__/ReservedTokensInputBlock.spec.js.snap
- src/components/stepThree/index.js
> (Fix) Gas price custom prevent invalid

- src/components/invest/index.js
Closes #577 
- Uses `decimals` to validate invest value
- Error message updated
> (Fix) Validate Invest Input

- src/components/manage/index.js
> (Fix) 'End date' modifiable after crwodsale was finalized

- src/components/stepThree/index.js
> (Fix) Fix gas price validation

- package-lock.json
- package.json
- src/components/Common/WhitelistInputBlock.js
- src/index.js
Closes #642.
Add Font Awesome dependency, add upload icon and move Upload CSV button to the bottom right.
> Move 'Upload CSV' button and add icon

- src/components/manage/index.js
- src/utils/alerts.js
> (Fix) Disable finalize button

- src/utils/utils.js
- src/utils/utils.spec.js
> (Fix) Fix token's name max length

- package-lock.json
- package.json
- src/index.js
> (Fix) Add airbnb JS shims

- src/components/crowdsale/utils.js
- src/components/invest/index.js
- src/stores/CrowdsalePageStore.js
- src/utils/alerts.js
Removing:
- `startBlock` method
- `endBlock` method
- `supply` method
- `investmentDisabledAlert` alert
> (Refactor) remove obsolete contracts methods and derivatives

- src/components/invest/index.js
> (Fix) Supply calculus for invest page

- src/components/stepThree/index.js
> (Fix) Prevent deployment if minCap isn't valid

- src/components/stepThree/index.js
Reverts poanetwork/token-wizard#693
> Revert "(Fix) Prevent deployment if minCap isn't valid"

- src/components/Common/ReservedTokensInputBlock.spec.js
- src/components/crowdsale/index.js
- src/components/crowdsale/utils.js
- src/components/invest/index.js
- src/components/manage/index.js
- src/components/manage/utils.js
- src/components/stepFour/index.js
- src/components/stepFour/utils.js
- src/components/stepOne/index.js
- src/components/stepThree/index.js
- src/components/stepThree/utils.spec.js
- src/stores/ContractStore.js
- src/utils/constants.js
Closes #536.
Remove all code involving different contract types, since we only have one kind of crowdsale and don't plan to add a different one (and if we eventually add one, the preemptive code and conditionals we have probably won't be that useful).
> (Refactor) Remove contract type checks

- src/components/Common/WhitelistInputBlock.js
- src/components/stepThree/__snapshots__/CrowdsaleBlock.spec.js.snap
- src/stores/TierStore.js
- src/stores/TierStore.spec.js
- src/utils/alerts.js
Closes #644.
In the step three page, the "Clear all" button shows up if there are added addresses. In the manage page, it shows if there are _new_ added addresses.
> (Feature) Add bulk delete for whitelists

- src/components/stepThree/index.js
> (Fix) Change min cap description

- src/components/invest/CountdownTimer.js
- src/components/invest/CountdownTimer.spec.js
- src/components/invest/__snapshots__/CountdownTimer.spec.js.snap
- src/components/invest/index.js
> (Fix) Stop countdown if crowdsale is finalized

- src/components/manage/utils.js
- src/components/stepFour/utils.js
> (Fix) Use bigNumber to operate with supply value

- package.json
- src/components/Common/CrowdsaleEndTime.js
- src/components/Common/CrowdsaleRate.js
- src/components/Common/CrowdsaleStartTime.js
- src/components/Common/CrowdsaleSupply.js
- src/components/crowdsale/utils.js
- src/components/manage/AboutCrowdsale.js
- src/components/manage/AboutCrowdsale.spec.js
- src/components/manage/DistributeTokensStep.js
- src/components/manage/DistributeTokensStep.spec.js
- src/components/manage/FinalizeCrowdsaleStep.js
- src/components/manage/FinalizeCrowdsaleStep.spec.js
- src/components/manage/ManageForm.js
- src/components/manage/ManageForm.spec.js
- src/components/manage/ManageTierBlock.js
- src/components/manage/ManageTierBlock.spec.js
- src/components/manage/ReadOnlyWhitelistAddresses.js
- src/components/manage/ReadOnlyWhitelistAddresses.spec.js
- src/components/manage/__snapshots__/AboutCrowdsale.spec.js.snap
- src/components/manage/__snapshots__/DistributeTokensStep.spec.js.snap
- src/components/manage/__snapshots__/FinalizeCrowdsaleStep.spec.js.snap
- src/components/manage/__snapshots__/ManageForm.spec.js.snap
- src/components/manage/__snapshots__/ManageTierBlock.spec.js.snap
- src/components/manage/__snapshots__/ReadOnlyWhitelistAddresses.spec.js.snap
- src/components/manage/index.js
- src/components/stepThree/index.js
- src/utils/validations.js
- src/utils/validations.spec.js
> (Refactor) Manage page final form

- src/components/Common/TierBlock.js
- src/components/Common/TokenDecimals.js
- src/components/Common/TokenDecimals.spec.js
- src/components/Common/TokenName.js
- src/components/Common/TokenName.spec.js
- src/components/Common/TokenTicker.js
- src/components/Common/TokenTicker.spec.js
- src/components/Common/__snapshots__/TokenDecimals.spec.js.snap
- src/components/Common/__snapshots__/TokenName.spec.js.snap
- src/components/Common/__snapshots__/TokenTicker.spec.js.snap
- src/components/manage/__snapshots__/ManageForm.spec.js.snap
- src/components/manage/__snapshots__/ManageTierBlock.spec.js.snap
- src/components/stepTwo/StepTwoForm.js
- src/components/stepTwo/index.js
- src/utils/constants.js
- src/utils/validations.js
- src/utils/validations.spec.js
> (Fix) Accept decimals reserved tokens

- src/components/Common/ReservedTokensInputBlock.js
- src/components/Common/TierBlock.js
- src/components/Common/TokenDecimals.js
- src/components/Common/TokenDecimals.spec.js
- src/components/Common/TokenName.js
- src/components/Common/TokenName.spec.js
- src/components/Common/TokenTicker.js
- src/components/Common/TokenTicker.spec.js
- src/components/Common/__snapshots__/TokenDecimals.spec.js.snap
- src/components/Common/__snapshots__/TokenName.spec.js.snap
- src/components/Common/__snapshots__/TokenTicker.spec.js.snap
- src/components/manage/__snapshots__/ManageForm.spec.js.snap
- src/components/manage/__snapshots__/ManageTierBlock.spec.js.snap
- src/components/stepTwo/StepTwoForm.js
- src/components/stepTwo/index.js
- src/utils/constants.js
- src/utils/processReservedTokens.js
- src/utils/processReservedTokens.spec.js
- src/utils/validations.js
- src/utils/validations.spec.js
> (Fix) Validate reserved value on bulk upload

- src/components/Common/InputField.js
- src/components/Common/__snapshots__/AddressInput.spec.js.snap
- src/components/Common/__snapshots__/BigNumberInput.spec.js.snap
- src/components/Common/__snapshots__/NumericInput.spec.js.snap
- src/components/Common/__snapshots__/ReservedTokensInputBlock.spec.js.snap
- src/components/stepThree/__snapshots__/CrowdsaleBlock.spec.js.snap
> (Fix) Add class 'error' to InputField

- src/components/stepThree/StepThreeForm.js
- src/components/stepThree/index.js
> (Fix) Trigger minCap-supply validation after supply has been changed

- src/components/manage/utils.js
> (Fix) Set string representation for whitelists' min/max values

- src/components/crowdsale/utils.js
- src/components/invest/index.js
Fixes #872
maxCap was not properly calculated for minted Capped strategy.
Also I moved wei rounding to where where it should be, right before send the tx.
> Real max cap

- src/components/Common/DutchAuctionBlock.js
> (Fix) Validate min/max rate for dutch auction crowdsale

- src/App.js
- src/components/stats/index.js
- src/utils/blockchainHelpers.js
Closes #620
Token Wizard statistics new metrics:
- future crowdsales amount
- past crowdsales amount
- ongoing crowldsales amount
Also,
- Only sane crowdsales are accounted
- % of finalized crowdsales is accounted from past crowdsales
> (Fix) Statistics new metrics: ongoing, future, past crowdsales

- src/components/manage/ManageTierBlock.js
- src/components/manage/index.js
- src/components/manage/utils.js
Closes https://github.com/poanetwork/token-wizard/issues/903
Save button doesn't make any actions now if no updates of tiers duration or whitelists.
> (Fix) Disable save button if there is no changes

- src/components/invest/index.js
- src/utils/alerts.js
> (Fix) Warning message for non whitelisted account

- src/components/crowdsale/utils.js
- src/components/manage/index.js
Closes #907 
Retrieving of tiers' amount and dates (start date and end date) is fixed for invest page
> (Fix) Invest multiple tiers fix

- src/components/stepFour/utils.js
Closes #923 
Mitigation of summary file download error if a user increases the gas price through Metamask during the deployment process.
> (Fix) Mitigation of file download error

- src/components/stepFour/index.js
- src/components/stepFour/utils.js
Closes #927 
Also,
- refactoring of rendering of Publish page
- minor fixes for summary files
> (Fix) remove unused parameter 'Allow modifying' from publish page in Dutch Auction strategy

- src/components/crowdsale/index.js
- src/components/crowdsale/utils.js
- src/components/manage/DistributeTokensStep.js
- src/components/manage/index.js
- src/components/stepFour/index.js
- src/components/stepFour/utils.js
- src/components/stepThree/StepThreeFormDutchAuction.js
- src/components/stepTwo/StepTwoForm.js
- src/stores/CrowdsaleStore.js
- src/utils/alerts.js
- src/utils/blockchainHelpers.js
Collapse `deployCrowdsale` and `deployDutchAuctionCrowdsale` to one function in deployment step.
Also
- Resolving of React fixes suggestions
> (Refactoring) collapse deployCrowdsale and deployDutchAuctionCrowdsale to one function

- src/components/manage/index.js
> (Fix) Wrong tiers' duration calculation

- src/components/manage/ManageForm.spec.js
- src/components/manage/ManageTierBlock.js
- src/components/manage/__snapshots__/ManageForm.spec.js.snap
- src/components/manage/index.js
- src/stores/TierStore.js
> Allow whitelist editing even if tier is not editable

- src/components/stats/index.js
Statistics: maxEthRaised value for both startegies is fixed in stats
> (Fix) Statistics: maxEthRaised fix in stats

- src/utils/blockchainHelpers.js
This is a refactor around `getApplicationsInstances` implementation. For maintainability/readability.
> (Refactor) getApplicationsInstances method

- src/components/crowdsale/utils.js
- src/components/stepFour/utils.js
Closes https://github.com/poanetwork/token-wizard/issues/977
Closes https://github.com/poanetwork/token-wizard/issues/978
display correct min cap in contribution page
> (Fix) display correct min cap in contribution page

- package-lock.json
- src/components/contribute/index.js
- src/components/crowdsale/index.js
- src/components/crowdsale/utils.js
- src/components/manage/index.js
- src/components/manage/utils.js
- src/components/stats/index.js
- src/components/stepFour/utils.js
- src/utils/utils.js
- src/utils/validations.js
- test/utils/validations.spec.js
> (Feature) toBigNumber signature change

- src/components/manage/ManageDutchAuctionBlock.js
- src/components/manage/utils.js
- src/utils/constants.js
Closes #976
- Added min & max rate values
- Changed 'rate' label to 'Current Rate'
> (Feature) Display min / max rates for Dutch Auction in manage page

- src/components/stepThree/index.js
- src/stores/DeploymentStore.js
Closes #1019
- Detect if Dutch Auction has MinCap
- Add parameter hasMinCap to function initialize
- Apply parameter to property required in TX
> (Bug) Excess tx to update global min cap for Dutch Auction

- src/components/stepThree/StepThreeFormDutchAuction.js
- src/components/stepThree/index.js
- src/components/stepTwo/index.js
- src/stores/TokenStore.js
- src/utils/blockchainHelpers.js
- src/utils/constants.js
Closes #1015 
- Add decimal constant for token
See image
> (Fix) make default token visibility 18 decimals 

- src/components/manage/index.js
Closes #1026
- Added new validation related to latest tier
> (Bug) Minted-Multitier: allow owner to finalize before end of crowdsale if all tokens were sold in latest tier

- package-lock.json
- package.json
- src/components/contribute/index.js
- src/components/crowdsale/utils.js
- src/utils/blockchainHelpers.js
- src/utils/utils.js
Closes #986 
- Added function to get user token balance
- Check token balance before and after purchase
> (Bug) Contribution confirmation popup

- src/App.js
- src/components/Common/ButtonContinue.js
- src/components/Home/index.js
- src/components/stepOne/index.js
- src/stores/ContractStore.js
- src/stores/CrowdsaleStore.js
- src/stores/DeploymentStore.js
- src/stores/GasPriceStore.js
- src/stores/GeneralStore.js
- src/stores/ReservedTokenStore.js
- src/stores/index.js
- src/utils/blockchainHelpers.js
- src/utils/utils.js
This is an integration PR for the step 1.
How to test it and what to test:
- Go to the home
- Create a crowdsale
- In the first step, press button "New crowdsale"
- Select the type of strategy
- Go to the second step
- Go back to step 1
- Should keep the selected strategy
- Refresh the step 1 page
- Should keep the selected strategy
- Go to the home, and press button "New crowdsale"
- The selected strategy must be the default, "WHITELIST WITH CAP"
The branch 2.0-integration must not be closed
Next steps to integrate:
> (Bug) Keep data between the steps (Step 1)

- src/components/contribute/index.js
- src/components/crowdsale/index.js
- src/components/manage/index.js
- src/utils/alerts.js
- src/utils/utils.js
Closes #1044
How to test it:
https://www.useloom.com/share/d3613258b92d4d1c91d1d931227e2b7e
Test run:
> (Fix) Add invalidCrowdsaleProxyAlert

- src/components/Common/NoWeb3.js
- src/components/contribute/ContributeForm.js
- src/components/contribute/index.js
- src/utils/alerts.js
- src/utils/blockchainHelpers.js
- test/components/contribute/__snapshots__/ContributeForm.spec.js.snap
> (Feature) Warning message: change word 'Metamask'

- src/components/Common/config.js
- src/components/crowdsale/index.js
- src/components/crowdsale/utils.js
- src/utils/utils.js
> (Fix) crowdsale config should support exec-id and address of proxy as well

- src/components/stepFour/constants.js
- src/components/stepFour/index.js
- src/utils/constants.js
Closes #1039 
Displays the information above the proxy Contract source code.
> (Feature) Add proxy name, compiler version and optimization info to publish page

- src/components/stepFour/index.js
Closes #1040 
- Added source code of proxy smart contract to zip archive
> (Feature) Source code of Proxy smart-contract should be added to zip archive for download

- src/components/stepFour/utils.js
> (Feature) metadata should be added to zip archive for download

- src/stores/utils.js
- test/components/Home/index.spec.js
> (Fix) Tests for Home Component

- src/components/stepOne/index.js
> (Refactoring) Duplicated line of code in master

- src/components/Common/ReservedTokensInputBlock.js
> (Fix) Reserved Token Addresses CSV import

- src/App.js
- src/components/Crowdsales/index.js
- src/components/Home/utils.js
- src/components/StepOne/index.js
- src/index.js
- src/stores/Web3Store.js
- src/utils/blockchainHelpers.js
> (Bug) New design-Home page: unhandled exception in browser's console if wallet isn't installed

- src/components/Common/CrowdsalesList.js
- src/components/Crowdsales/index.js
- src/components/Home/ChooseCrowdsale.js
- src/components/Home/CreateCrowdsale.js
- src/components/StepOne/index.js
- src/utils/utils.js
- test/components/StepOne/__snapshots__/index.spec.js.snap
- test/utils/utils.spec.js
> (Bug) Step 1: selected strategy isn't kept after refreshing or moving back/forward

- package-lock.json
- src/components/StepOne/index.js
- test/components/StepOne/index.spec.js
> (Fix) Home [New Crowdsale] button is not cleaning the localStorage

- src/components/crowdsale/utils.js
> (Fix) contribution page incorrect min contribution for multitier crowdsale

- src/components/contribute/index.js
> (Feature) Update contribution page if account was switched in wallet

- src/components/StepThree/GasPriceInput.js
> (Bug) Step3: field gas price custom empty by default 

- src/components/StepThree/GasPriceInput.js
> (Bug) Step3: field gas price custom empty by default

- src/components/StepOne/index.js
- src/components/StepThree/index.js
- src/components/StepTwo/index.js
- src/react-web3/Web3Provider.js
- test/components/StepOne/__snapshots__/index.spec.js.snap
- test/components/StepThree/__snapshots__/index.spec.js.snap
> (Bug) NoWeb3 screen flashes

- src/components/StepFour/index.js
- src/components/StepOne/index.js
- src/components/StepThree/index.js
- src/components/StepTwo/index.js
> Add before unload warning

- src/components/Common/DutchAuctionBlock.js
- src/components/StepThree/StepThreeFormDutchAuction.js
- test/components/StepThree/__snapshots__/StepThreeFormDutchAuction.spec.js.snap
- test/components/StepThree/__snapshots__/index.spec.js.snap
> (Bug) Dutch -Step3: allowed to add whitelist if the supply field is empty

- README.md
> Update support status
