- src/utils/microservices.js
Relates to https://github.com/oraclesorg/ico-wizard/issues/302
> ABI encoded parameters without 0x

- src/components/invest/index.js
Closes #273 (https://github.com/oraclesorg/ico-wizard/issues/273#issuecomment-341449487)
- Displays error message if the user tries to Invest without entering a valid token amount.
- Moved input's pristine flag, into the Component's state.
> (Fix) No error message on invest form submit

- src/components/stepFour/constants.js
- src/components/stepFour/index.js
Closes #270 
- Added a toaster informing the user that the contract was properly downloaded on the PC.
- Moved the Contract Download option after the last transaction, to avoid "Loading" overlay and "Toaster" overlapping.
> (Feature) Toaster on contract download

- src/utils/microservices.js
Closes #302
`0x` prefix is removed from ABI encoded parameters in the downloaded file
> (Fix) 0x prefix removed from ABI encoded parameters

- .github/ISSUE_TEMPLATE.md
There have been several reported issues that don't provide some basic information. This adds a template so that people opening bugs can know which is the minimal data that they should include with the report.
> (Chore) Add issue template

- src/components/Common/CrowdsaleBlock.js
- src/components/stepThree/index.js
- src/stores/TierStore.js
- src/utils/constants.js
- src/utils/utils.js
Closes #233 
- validation for end time > start time for 2nd tier and further
- validation, that start time of the tier cannot be less than end time of the previous tier
- validation, before continuing checks that the dates are valid (i.e.: start date can be set later than end date, and wasn't validated properly)
> (Fix) Time validations step3

- package.json
- src/utils/alerts.js
I would like to propose to switch from SweetAlert to [SweetAlert2](https://github.com/limonte/sweetalert2) - the supported fork of SweetAlert. The original reason for creating SweetAlert2 is the inactivity of SweetAlert: https://stackoverflow.com/a/27842854/1331425 
1. Accessibility (WAI-ARIA) - SweetAlert2 is fully WAI-ARIA compatible and supports all popular screen-readers. Accessibility is a must in 2017, there are a lot of explanatory and tech articles, but this one is truly inspirable: [Software development 450 words per minute](https://www.vincit.fi/en/blog/software-development-450-words-per-minute/)
2. Better buttons contrast is a huge advantage for all users especially for users with vision disabilities. 
3. Better support, average time to resolve an issue:
- SweetAlert: …
> (Refactor) Switch from SweetAlert to SweetAlert2

- README.md
**Problem**: outdated organization name for Travis CI, Waffle links in README
**Solution**: update links in README
> (Emergency) Update Travis CI, Waffle links in README

- scripts/compileContract.js
Closes #425 
**Problem**: autogenerated header in contracts source files is outdated (previous organization and network names)
**Solution**: change autogenerated header in contracts source files
> (Fix) Updated autogenerated header in contracts source files

- src/components/crowdsale/utils.js
Closes #451 
**Problem**: Crowdsale page doesn't show correct total raised value and progress bar value
**Solution**: Avoid scientific notation of big numbers
> (Fix) crowdsale page ETH raised value

- .gitmodules
- package-lock.json
- src/components/crowdsale/utils.js
- src/utils/utils.js
Relates to https://github.com/poanetwork/web3.js/issues/1
**Problem**: web3 is outdated
**Solution**: get upstream from web3.js@1.0.0-beta.27 and merge
> (Fix) web3.js@1.0.0-beta.27 upstream merged

- src/components/stepThree/index.js
Deployment to Mainnet is down for maintenance due to wizard contracts audit.
> (Emergency) Mainnet is down for maintenance warning due to audit

- src/components/invest/index.js
The invest page doesn't seem to be working because of this.
`web3.eth.accounts` has a different behavior in web3 1.0. Not sure why this was working before.
> (Fix) Use eth.getAccounts() instead of eth.accounts

- package.json
- src/components/Common/RadioInputField.js
- src/components/Common/RadioInputField.spec.js
- src/components/Common/ReservedTokensInputBlock.js
- src/components/Common/__snapshots__/RadioInputField.spec.js.snap
- src/components/stepThree/CrowdsaleBlock.js
- src/components/stepThree/index.js
- src/utils/blockchainHelpers.spec.js
Closes #442.
This PR makes RadioInputField acccept more than two options, and improves a little its code. It also adds tests for the component.
I thought about using it for the gas price selector, but that component is special because it shows an input when you select a custom gas price, so I ended up leaving it as it was.
> (Refactor) Refactor RadioInputField and add tests

- src/components/manage/utils.js
> (Fix) manage crowdsale to allow edit if it didn't started yet

- .gitmodules
- package-lock.json
- package.json
- src/components/crowdsale/index.js
- src/components/crowdsale/utils.js
- src/components/invest/index.js
- src/components/manage/index.js
- src/components/manage/utils.js
- src/components/stepFour/index.js
- src/components/stepFour/utils.js
- src/stores/DeploymentStore.js
- src/stores/GasPriceStore.js
- src/stores/GasPriceStore.spec.js
- src/utils/__mocks__/api.js
- src/utils/__mocks__/gasPrice.json
- src/utils/alerts.js
- src/utils/api.js
- src/utils/constants.js
- src/utils/utils.js
As a result of security audit, contracts were updated with these PRs: https://github.com/poanetwork/ico/pull/14, https://github.com/poanetwork/ico/pull/15, https://github.com/poanetwork/ico/pull/16, https://github.com/poanetwork/ico/pull/17, https://github.com/poanetwork/ico/pull/18, https://github.com/poanetwork/ico/pull/19, https://github.com/poanetwork/ico/pull/20, https://github.com/poanetwork/ico/pull/21, https://github.com/poanetwork/ico/pull/22
Changes should be implemented in ICO Wizard due to audit:
- Finalization is in two steps: distribute reserved tokens (with batches) -> finalization
- `setTier` instead of `setLastCrowdsale` for PricingStrategy contract
- `setEarlyParticipantsWhitelist` renamed to `setEarlyParticipantWhitelistMultiple`
- `updateRate` is from crowdsale …
> (Fix) Updated contracts after security audit

- package-lock.json
- package.json
`ganache-cli` is giving us some issues in the invest and manage pages (not really sure about the problem, but it seemed to be related with the gas estimation).
Upgrading it to `6.1.0-beta.0` seems to fix it. Since it's a dev dependency I think we'll be OK with using a beta version.
> (Chore) Upgrade ganache-cli

- src/components/stepFour/index.js
Closes #566 
Seems that the user closed the deployment steps modal, and the process was lacking of the option to close the _loading_ overlay.
> (Fix) loader not loading after deployment has finished

- src/components/stepFour/index.js
- src/stores/ContractStore.js
- src/stores/CrowdsaleBlockListStore.js
- src/stores/CrowdsalePageStore.js
- src/stores/CrowdsaleStore.js
- src/stores/DeploymentStore.js
- src/stores/GasPriceStore.js
- src/stores/GeneralStore.js
- src/stores/InvestStore.js
- src/stores/PricingStrategyStore.js
- src/stores/ReservedTokenStore.js
- src/stores/StepThreeValidationStore.js
- src/stores/StepTwoValidationStore.js
- src/stores/TierCrowdsaleListStore.js
- src/stores/TierStore.js
- src/stores/TokenStore.js
- src/stores/Web3Store.js
- src/stores/index.js
- src/utils/utils.js
This is the second step towards #529.
This simply checks if the `deploymentStep` in local storage is null. If that's the case, the local storage is cleared. If not, then it means a deployment is in progress, so the storage is left untouched. It also sets the `deploymentStep` to null when the deploy is finished.
Most of the other changes consist of moving the creation of the stores to `stores/index.js`: this is necessary to be able to execute some code before the stores are created.
> (Feature) Clear localStorage at start if there is no deploy in progress

- src/components/stepFour/index.js
- src/utils/executeSequentially.js
- src/utils/executeSequentially.spec.js
Part of #529.
This fixes an issue that @fernandomg found: the deploy was resumable if a transaction had failed and you refreshed the browser, but if the browser was closed during or after a successful transaction, then the deploy would resume from the beginning (or the last failed step).
> (Feature) Save deploymentStep in each step

- src/App.js
- src/components/IncompleteDeploy.js
Part of #529.
Show a message if there is an incomplete deploy, and allow resuming or canceling it:
The styles could be better, and the "Cancel" button should show a warning explaining that the user will lose all the gas inverted in the deploy. But I want to check if this approach makes sense to you before doing further changes.
> Check if there is an unfinished deploy

- src/components/IncompleteDeploy.js
- src/components/stepFour/index.js
- src/utils/alerts.js
Part of #529.
Two additions to the resume deployment feature:
- Show a warning when the user cancels a deployment in progress (please check the warning message and tell me if it's OK).
- Don't show the progress modal if the deployment has already finished (this fixes an issue that appears when you refresh the page in step four after the deploy finished: the modal was shown but there was no way to close it).
> (Feature) Improve deployment resume

- src/components/Common/TxProgressStatus.js
- src/components/IncompleteDeploy.js
- src/components/stepFour/index.js
- src/stores/DeploymentStore.js
- src/utils/alerts.js
Depends on #594.
This is the last part of #529. If this is approved, I will create a PR for the feature branch against master.
Show a skip button if a transaction fails. This is a workaround for the problem of repeated transactions. The scenario is this: suppose that a transaction can only be done once, and it fails if it's repeated. Suppose too that the deploy is in a step that performs a transaction like that. Then:
1. MetaMask shows the popup for submitting that transaction.
2. The user's browser crashes or they refresh the page.
3. The deployment is resumed, and the same transaction is sent through MetaMask. Now MetaMask has two equal transactions in the queue, but the app only responds to the result of the second one.
4. The user submits both transactions. The first one is …
> (Feature) Show skip button if transaction fails.

- src/components/Common/InputField.js
- src/components/Common/NumericInput.js
- src/components/Common/NumericInput.spec.js
- src/components/Common/__snapshots__/NumericInput.spec.js.snap
- src/components/Common/__snapshots__/ReservedTokensInputBlock.spec.js.snap
- src/components/stepTwo/index.js
- src/utils/utils.js
- src/utils/utils.spec.js
Closes #568 
Created a new component (`NumericInput`) whose intention is to be used across all the wizard where a number is required.
I just updated the **DECIMALS** input field for `stepTwo` with this new component
> (Fix) Add validation to decimals

- src/utils/blockchainHelpers.js
We shouldn't handle an error from the previous deployment tx, if it is already mined in `repeatPolling()` of tx receipt. Possible fix for https://github.com/poanetwork/token-wizard/issues/603
> (Fix) check isMined on error event

- README.md
The coveralls badge was pointing to the `add-coveralls` branch instead of `master`.
> (Fix) Fix coveralls badge

- src/App.js
Closes #626.
For the record, this was happening always after the deploy was complete. It's not necessary to make an incomplete deploy first.
> (Fix) Don't render IncompleteDeploy in step 4

- src/components/stepThree/index.js
- src/stores/TierStore.js
- src/stores/TierStore.spec.js
- src/utils/constants.js
Closes #621.
This checks that the min cap isn't greater than _any_ supply, not the sum of all the supplies. Otherwise, it may be the case that you can't buy in any tier.
For example, if you have a tier with supply 10 and another with supply 5, and your min cap is 11, it's less than the sum of all supplies, but you can't buy in none of the tiers.
I don't like at all the error message in this fix: it shows a message that basically says "this field is wrong, and one of these three things is the one causing the error".
It would be much better UI to show only the messages that are relevant. For example, if you input "-1" it just says "Value must be positive". If you input "1.333" and the token only has two decimals, it says "Decimals should not exceed...". If you input "-1.333", it should show …
> (Fix) Don't continue to step 4 if min cap is not valid

- src/components/Common/WhitelistInputBlock.js
- src/utils/alerts.js
- src/utils/processWhitelist.js
- src/utils/processWhitelist.spec.js
Depends on #642. Closes #640.
Give some very basic feedback to the user after importing a whitelist CSV. We can iterate over this to give better feedback if needed (for example, this doesn't show how many malformed rows were skipped, nor indicates if the imported CSV had addresses that were already added, and therefore ignored).
> (Feature) Indicate to user how many addresses were imported to the whitelist

- src/components/stepFour/index.js
Fixes #593 (the underlying issue).
Switching networks may cause a lot of issues, and I'm not sure we can (or should) fix them all. For example, if you switch networks in the middle of a deployment, you'll be allowed to continue, but the deploy will of course fail.
I guess we could save the id of the network where the deployment started, and alert the user that they are in a different network. But I wouldn't try anything more clever than that (for example, persisting different incomplete deployments in the local storage according to the network that is being used).
> (Fix) Set deploymentStep when starting step four

- src/components/Common/WhitelistInputBlock.js
- src/utils/alerts.js
- src/utils/processWhitelist.js
- src/utils/processWhitelist.spec.js
> (Feature) Validate imported whitelist addresses

- README.md
Fix the link in README to `Deployment Time & Gas` section in wiki
> (Fix) link to Deployment Time & Gas in README

- src/components/Common/TxProgressStatus.js
- src/components/stepFour/index.js
For now, e2e tests work with production environment and fail with dev environment. This is because of different interfaces for dev and prod. At least "Deploy" button exists in step 4 in a dev environment and it is hidden in prod environment 
1. create different e2e scripts for local and prod environments
2. adjust a local environment to fit prod one.
PR implements the 2nd approach.
> (Fix) unify dev and prod interfaces

- src/components/crowdsale/utils.js
Closes #706 
In spite of what's pointed out in the bug details, this bug was caused by treating values returned by contracts as numbers and not as `bigNumber`.
There were values not being properly converted: `weiRaised` and `tokensSold`. And to prevent any possible issue, I also did changes to `investors`.
> (Fix) Cast to bigNumber values returned by contracts

- src/App.js
See https://github.com/poanetwork/token-wizard/pull/680#issuecomment-376289139
This should allow users to go to the invest page without metamask.
Our routes are becoming too complex. I have some ideas on how to improve them, but for now this fix should be enough.
> (Fix) Make invest available even if there is no injected web3

- src/components/stepTwo/StepTwoForm.js
- src/components/stepTwo/StepTwoForm.spec.js
- src/components/stepTwo/__snapshots__/StepTwoForm.spec.js.snap
- src/components/stepTwo/index.js
After #719, the "Name", "Ticker" and "Decimals" field were ported to final-form. Our idea was to make the reserved tokens block with final-form too, but given how this block works, it is kind of difficult. So I just included it inside the form but without "translating" it to the final-form way of doing things.
Doing it the right way would mean having something like a group of inputs for each added token. This would be good not only because it would use the final-form features; it would also work as a solution for #486. I also think it'd be a nicer UI: you can edit each reserved token in-place, and have validation feedback if there are repeated reservations (instead of overwriting the entry, like we're doing now).
> (Refactor) Use ReservedTokensInputBlock inside final-form

- src/components/invest/index.js
Closes #754.
`setTimeout` may not work when the given value is greater than 2147483647 (approximately 24 days). This adds a check so that the timeout is only set if it's less than a day away.
See [this SO question](https://stackoverflow.com/questions/3468607/why-does-settimeout-break-for-large-millisecond-delay-values) for more information.
> (Fix) Fix countdown not displaying days

- src/components/manage/index.js
- src/components/manage/utils.js
- src/components/manage/utils.spec.js
Closes #728.
When updating fields, perform the transactions for the tiers in reverse order (the last tier first, then the second-to-last, etc.). Within tiers, update the end date before the start date. This way both the start and end date can be updated at the same time even if the new start date is after the old end date.
> (Fix) Update fields in reverse order and endTimes before startTimes

- src/components/invest/index.js
> (Fix) Make countdown work when next tier is more than 30 days away

- src/components/invest/index.js
Closes #765.
We were using JS numbers to compute the amount of weis to send in the invest page, which was getting wrong results (I guess because of an overflow?).
This PR uses `BigNumber` to perform the computation.
> (Fix) Use BigNumber in invest page

- src/components/Common/InputField2.js
- src/components/crowdsale/utils.js
- src/components/invest/InvestForm.js
- src/components/invest/InvestForm.spec.js
- src/components/invest/__snapshots__/InvestForm.spec.js.snap
- src/components/invest/index.js
Closes #785 & #797 
This PR:
- Implements `final-form` in the invest page and its validations for the input field
- Displays `balance` with all its decimals when valid
**note**: when `rate` isn't a divisor of `1e18`, the conversion to/from eth may lead to not precise values, for instance:
- using a rate of `151`,
- if user buys `2.1` tokens,
- balance will display: `2.100000000000000135` tokens
> (Refactor) Migrate invest page to final-form

- src/components/stepFour/index.js
- src/stores/ContractStore.js
- src/stores/utils.js
- src/utils/constants.js
**Problem**: users complain that they don't have `FlatPricingExt` source code and summary file. Also, summary file for `CrowdsaleTokenExt` contract doesn't include ABI encoded parameters.
**Solution**:  `deploymentStore.deploymentStep` never reaches `null` because it is set to `0` in the constructor. Thus, it should compare with `0` in `deployCrowdsale` function.
Also,
- obsolete `multisig` contract is removed from ContractStore
- obsolete `tokenTransferProxy` contract is removed from ContractStore
- archive prefix is renamed from `icowizard` to `tokenwizard`
> (Fix) Summary files fixes

- src/components/stepFour/utils.js
**Problem**: there are a few appeals like this https://forum.poa.network/t/stuck-at-token-wizard-step-4/1142/4 with the error: `Cannot read property 'rate' of undefined` on downloading of summary files. This error blocks downloading. Sometimes it is caused by increasing gas price in MetaMask (and [we don't recommend to do this](https://github.com/poanetwork/token-wizard/wiki/FAQ#13-i-confirmed-transaction-in-metamask-and-after-some-time-of-waiting-i-see-the-message-in-metamask-taking-too-long-retry-with-a-higher-gas-price-here-should-i-increase-gas)) but sometimes - by other reasons (we don't know those exactly)
**Solution**: As we can't repeat the same bug, I have added the check that both `content` and `type` are not empty (it will unlock downloading of the summary files) and additional …
> (Fix) handlerForFile function debug

- src/App.js
- src/components/invest/index.js
- src/stores/Web3Store.js
- src/utils/alerts.js
- src/utils/blockchainHelpers.js
Closes #866
**Problem**: crowdsale page is hidden if Metamask is not present
**Solution**: Since we introduced the connection to Infura for crowdsale and invest page here: https://github.com/poanetwork/token-wizard/pull/826 we should not hide crowdsale page anymore.
Also, minor fixes:
- `MetaMaskIsLockedAlert()` is introduced - if Metamask is installed but is locked
- `noDeploymentOnMainnetAlert()` is removed. It is duplicate of `mainnetIsOnMaintenance` alert
> (Fix) show crowdsale page if no Metamask

- src/stores/ContractStore.js
Closes #828
As a rule, every new _observable_ added to any store must be declared in the store itself.
> (Fix) Persist crowdsale deployment status

- src/utils/constants.js
Closes #950
Interfaces of events have been changed since Auth-os v.1.0.1:
`ApplicationException`:
https://github.com/auth-os/applications/blob/4d8c7149d031944d8b85de873b7f6875e9c49d55/TokenWizard/crowdsale/MintedCappedCrowdsale/test/auth_os/core/AbstractStorage.sol#L51
`StorageException`
https://github.com/auth-os/core/blob/79165be925b5aaebca18508f0118892da694c67a/contracts/core/ScriptExec.sol#L37
> (Fix) Update events' interfaces

- src/components/Common/DutchAuctionBlock.js
- src/components/Common/MinCap.js
- src/components/Common/TierBlock.js
- src/components/stepThree/index.js
- src/utils/validations.js
- src/utils/validations.spec.js
Closes #946
Since bug was reported, `globalMinCap` is no longer used. Now `minCap` is specified in a per-tier basis.
Anyway, this issue was used to track `minCap` validation in `StepThree`.
> (Fix) Min cap validate with supply

- src/components/crowdsale/index.js
Closes #815 
- Added `toFixed() ` function 
- See [bignumber docs](https://mikemcl.github.io/bignumber.js/#toFix) for more details
Image before fix:
Image after fix:
> (Fix) Total Raised Funds expressed in scientific notation

- src/components/stepFour/index.js
Closes #817 
- Remove DisplayField block from tiers
- The wallet address was added in the block of the crowdsale contract
- The tests were run successfully
Image before
Image after
Test executed
> (Feature) One wallet address for the whole summary 

- src/components/contribute/index.js
- src/components/manage/index.js
Closes #975 
- The field is_finalized  now takes into account whether it is a mintedcapped or dutch crowdsale
- Added variable to disable the button
See images
Crowdsale with all the tokens sold
Allow to finalize crowdsale before finish because all the tokens were sold
Disable button after finish
> (Bug) Button "Finalize" is active after finalization 

- src/components/manage/index.js
Closes #1016 
- Remove property from disable 
Note: 
There was a problem between the [PR #1007](https://github.com/poanetwork/token-wizard/pull/1007) and the [PR #1008](https://github.com/poanetwork/token-wizard/pull/1008) at the moment of merge, and the commit that solved this problem was lost. Now we incorporate it again.
>  (Bug)Dutch: button `finalize` disabled if crowdsale time over but not all tokens were sold

- src/components/Common/InputField.js
- src/components/Common/NumericInput.js
- src/components/Common/RadioInputField.js
- src/components/Common/ReservedTokensInputBlock.js
- src/components/Common/TierBlock.js
- src/components/manage/ManageForm.js
- src/components/manage/ManageTierBlock.js
- src/components/stepThree/GasPriceInput.js
Closes #790 
- Add 'id' to some input elements:
- Elements suggested by @dennis00010011b 
1. Step3: Whitelist - Address
2. Step3: Whitelist - Min
3. Step3: Whitelist - Max
4. Step3: Gasprice - Custom
5. Manage page: Start time
6. Manage page: End time
7. Manage page: Rate
8. Manage page: Supply
9. Manage page: Whitelist- Address
10. Manage page: Whitelist- Min
11. Manage page: Whitelist- Max
12. Manage page: Setup name
13. Manage page: Wallet address
> (Feature) Add selector 'id' to all DOM input elements 

- .travis.yml
- package-scripts.js
- package.json
- scripts/stop_port3000.sh
- e2e tests are  splitted into six parts
- individual  travis job for react components tests
- removed unused scripts from package.json
- refactored scripts in package-scripts.js
- refactored travis.yml: added cache option, job is splitted into 7 parts
> (Refactor) Speed up build in travisci

- src/components/Common/ReservedTokensInputBlock.js
- src/components/stepTwo/StepTwoForm.js
- src/components/stepTwo/index.js
- src/stores/ReservedTokenStore.js
- src/utils/alerts.js
- src/utils/constants.js
- src/utils/processReservedTokens.js
Closes #1048 
There is a limitation based on the contracts, see image
When you upload a file that exceeds 20 addresses, a message like this should appear, see image
- Added two new alerts to manage reserved slot address
- Add validation in the ReservedTokenStore
- Refactoring applying new validation
> (Bug) Reserved addresses are not initialized if list length > 20

- src/components/Common/WhitelistInputBlock.js
- src/stores/TierStore.js
- src/utils/alerts.js
- src/utils/constants.js
- src/utils/processWhitelist.js
Closes #1052 
The problem is also reproducible with values ​​lower than 60, and it is random
sometimes 59, sometimes 58, sometimes 60. I take the decision to put a limit of 50
- Add constant to limit whitelisted addresses to 50
- Add two new alerts for whitelisted addresses, when the validation is applied
- Refactor processWhitelist function
- Add function to validate whitelisted addresses length
- Apply whitelist validation to the component
> (Bug) Minted, Dutch: Whitelisted addresses are not initialized if list length > 60

- src/components/Common/ButtonContinue.js
- src/components/Common/DutchAuctionBlock.js
- src/components/Common/TierBlock.js
- src/components/stepThree/GasPriceInput.js
- src/components/stepThree/StepThreeFormDutchAuction.js
- src/components/stepThree/StepThreeFormMintedCapped.js
- src/components/stepThree/index.js
- src/stores/GeneralStore.js
- src/stores/TierStore.js
- src/stores/Web3Store.js
- src/utils/constants.js
- src/utils/utils.js
- test/components/manage/__snapshots__/ManageForm.spec.js.snap
- test/components/stepTwo/__snapshots__/StepTwoForm.spec.js.snap
This is an integration PR for the step 3.
How to test it and what to test:
- Go to the home
- Create a crowdsale
- In the first step, press button "New crowdsale"
- Select the type of strategy
- Go to the second step
- Go back to step 1
- Should keep the selected strategy
- Refresh the step 1 page
- Should keep the selected strategy
- Got to the second step
- Complete the form
- Refresh the page, should keep the data
- Add reserved tokens
- Refresh the page, should keep the data
- Got to the third step
- Complete the form
- Refresh the page, should keep the data
- Go to the home, and press button "New crowdsale"
- The selected strategy must be the default, "WHITELIST WITH CAP"
- Go to the second step
- The form must be empty
> (Bug) Keep data between the steps (Step 3)

- src/components/stepFour/index.js
- src/components/stepThree/GasPriceInput.js
- src/components/stepThree/index.js
- src/stores/GeneralStore.js
- src/stores/Web3Store.js
- src/utils/alerts.js
- src/utils/blockchainHelpers.js
- test/components/manage/__snapshots__/ManageForm.spec.js.snap
@dennis00010011b 
Can you check this two steps with this branch?
I Perform some tests and it seems to work well, I would need your expert eye
Thanks in advance
> (Bug) Keep data between the steps (Step 4 - Publish && Step 5 - Contribution Page)

- Dockerfile
Included `Dockerfile` contains `travis`, which may be helpful for running local test in a container before creating the PR.
Steps to use it:
1. install docker [https://docs.docker.com/install/#supported-platforms](https://docs.docker.com/install/#supported-platforms)
1. move to the project root
1. `docker build -t tw .` (where `tw` is the name of the docker image created and `.` is the location of the Dockerfile)
1. `docker run -ti tw`
1. once the image has started, run `travis compile > ci.sh`
1. edit `ci.sh` file and set the corresponding branch (search for `branch` word and replace: `branch\=\'\'` with `branch\=\'master\'`)
1. `bash ci.sh`
---
Docker build can receive three arguments `author`, `project`, `branch`.
Default values:
- `author`: `poanetwork`
- `project`: `token-wizard`
- …
> (Feature) Add dockerfile

- src/components/stepFour/index.js
Closes #1037 
I've just added sources for `.abi`, `.bin` and `.src`.
> (Feature) add source code of Proxy smart-contract to Publish page

- src/components/stepFour/index.js
- src/components/stepFour/utils.js
> (Feature) Add ABI-Encoded params for Proxy Contracts

- src/components/stepFour/index.js
- src/components/stepFour/utils.js
Closes #1101 
- Check strategy of the crowdsale
- Create labels regarding selected strategy
> (Bug) Dutch- Publish page: uploaded file'Auth-os_addresses.txt' contains wrong names of contracts

- src/components/stepFour/utils.js
Closes #1150
I try to reproduce the error in the sokol network without success
I think the crowdsale of the problem is using exec-id , and is not proxy
Here is the line where the logical decision is made
https://github.com/poanetwork/token-wizard/blob/2.0/src/components/stepFour/utils.js#L994
Can you checked @dennis00010011b ?
If you find a problem, can you make a comment with the steps to reproduce it?
Regards
> (Bug) There is no Proxy contract address in zip archive (Minted capped only) 

- package-lock.json
- package-scripts.js
- scripts/helpers/utils.js
The sequence of subtasks of `build` script is incorrect:
it copies everything to `build` folder and only then generates metadata for contracts. The reverse sequence should be. This PR fixes the issue.
> (Fix) Incorrect build sequence

- package-lock.json
- src/App.js
- src/App.spec.js
- src/__snapshots__/App.spec.js.snap
- src/components/Common/NoWeb3.js
- src/components/Common/NoWeb3.spec.js
- src/components/Home/__snapshots__/index.spec.js.snap
- src/components/Home/index.spec.js
- src/components/manage/index.js
- src/components/stepOne/index.js
- src/react-web3/Web3Provider.js
- src/react-web3/Web3Provider.spec.js
- src/react-web3/__snapshots__/Web3Provider.spec.js.snap
- src/stores/Web3Store.js
- src/utils/blockchainHelpers.js
Closes #1165 .
Modify the "MetaMask not found" error page to display a generic error text stating "Wallet not found, or access to Ethereum account not granted"
This is for the master branch, there will be another PR for the branch 2.0
> (Fix) Update DApp loading code considering upcoming Breaking Change in MetaMask (Branch Master)

- src/utils/utils.js
Closes #1195
@dennis00010011b 
If you change your local machine time and date like in video you can have problems with the SSL in the endpoint https://gasprice.poa.network/ ,  be careful with that.
> (Bug) Minted crowdsale: owner able to finalize before start
